query getPostsByCategory($slug: ID!, $first: Int!) {
  category(id: $slug, idType: SLUG) {
    name
    posts(first: $first, where: { status: PUBLISH }) {
      nodes {
        databaseId
        title
        link
        slug
        date
        excerpt(format: RENDERED)
        commentCount
        featuredImage {
          node {
            sourceUrl
            mediaDetails {
              width
              height
              sizes {
                sourceUrl
                height
                width
                name
              }
            }
          }
        }
        categories(where: { orderby: COUNT }) {
          nodes {
            name
            slug
          }
        }
      }
    }
  }
}
