query GetPost($slug: ID!) {
  post(id: $slug, idType: SLUG) {
    databaseId
    title
    link
    slug
    content(format: RENDERED)
    excerpt(format: RENDERED)
    date
    commentCount
    featuredImage {
      node {
        sourceUrl
        mediaDetails {
          width
          height
          sizes {
            sourceUrl
            height
            width
            name
          }
        }
      }
    }
    author {
      node {
        name
        slug
        avatar {
          url
        }
      }
    }
    categories(where: { orderby: COUNT }) {
      nodes {
        databaseId
        name
        slug
      }
    }
    tags {
      nodes {
        databaseId
        name
        slug
      }
    }
    comments(first: 30, where: { statusIn: APPROVE, order: ASC }) {
      nodes {
        databaseId
        date
        status
        content(format: RENDERED)
        author {
          node {
            name
            url
            email
            avatar {
              url
            }
          }
        }
      }
    }
  }
}
