# import "./fragments.gql"

mutation CreateComment(
  $author: String!
  $authorEmail: String!
  $content: String!
  $postId: Int!
  $clientMutationId: String = "createComment"
) {
  createComment(
    input: {
      author: $author
      authorEmail: $authorEmail
      content: $content
      commentOn: $postId
      clientMutationId: $clientMutationId
    }
  ) {
    success
    comment {
      ...CommentDetails
    }
  }
}

mutation RefreshAuthToken($token: String!) {
  refreshToken(input: { refreshToken: $token }) {
    authToken
    success
  }
}
