# import "./fragments.gql"

query GetPosts($first: Int!) {
  posts(first: $first) {
    nodes {
      ...PostsDetails
    }
  }
}

query GetPostsBySearch($search: String = "", $first: Int!) {
  posts(where: { search: $search }, first: $first) {
    nodes {
      ...PostsDetails
    }
  }
}

query GetPostsByAuthor($slug: ID!, $first: Int!) {
  user(id: $slug, idType: SLUG) {
    name
    posts(first: $first) {
      nodes {
        ...PostsDetails
      }
    }
  }
}

query GetPostsByCategory($slug: ID!, $first: Int!) {
  category(id: $slug, idType: SLUG) {
    name
    posts(first: $first) {
      nodes {
        ...PostsDetails
      }
    }
  }
}

query GetPostsByTag($slug: ID!, $first: Int!) {
  tag(id: $slug, idType: SLUG) {
    name
    posts(first: $first) {
      nodes {
        ...PostsDetails
      }
    }
  }
}

query GetComments($contentId: ID!, $first: Int!) {
  comments(
    first: $first
    where: {
      contentId: $contentId
      contentStatus: PUBLISH
      contentType: POST
      statusIn: APPROVE
      parentIn: "null"
    }
  ) {
    nodes {
      ...CommentDetails
    }
  }
}

query GetPost($slug: ID!, $idType: PostIdType!, $isPreview: Boolean = false) {
  post(id: $slug, idType: $idType, asPreview: $isPreview) {
    ...PostDetails
  }
}

query GetPage($slug: ID = "URI") {
  page(id: $slug, idType: URI) {
    id
    date
    slug
    title(format: RENDERED)
    content(format: RENDERED)
    featuredImage {
      node {
        ...MediaItemFields
      }
    }
    seo {
      title
      description
      focusKeywords
      robots
      canonicalUrl
      openGraph {
        title
        description
        siteName
        type
        url
        updatedTime
        twitterMeta {
          card
          description
          title
          image
        }
        image {
          width
          height
          type
          secureUrl
          url
        }
      }
    }
  }
}

query GetSitemapPostsAndPages($first: Int = 200) {
  pages(first: $first) {
    nodes {
      slug
      modified
      seo {
        canonicalUrl
        focusKeywords
        robots
      }
    }
  }
  posts(first: $first) {
    nodes {
      slug
      modified
      seo {
        canonicalUrl
        focusKeywords
        robots
      }
    }
  }
}

query GetMenuItems {
  menuItems(where: { location: PRIMARY }) {
    nodes {
      id
      label
      url
    }
  }
}
